"""Stage 2-draft (was Stage D) — bilingual card drafter, per candidate.

Per `docs/ARCHITECTURE_RESET.md`:

- Stage 2-draft takes one `module_candidate_draft` and produces an
  auto-published Module with `module_json.cards` populated. Quiz +
  embedding generation are separate post-publish Celery workers; this
  stage enqueues both via `_enqueue_post_publish` once the module row
  has been committed.
- Reviewer-as-gate is gone. Modules publish straight to
  `lifecycle_status='published'` with `clinically_reviewed=false`. The
  admin dashboard surfaces them for inspection/correction.
- `module_card_validator` runs on each drafted card; cards with hard
  violations are dropped, soft warnings are annotated as `field_flags`.
- If the validator strips the module below `card_min_count`, the candidate
  is skipped (auto-publish principle: only renderable modules ship).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from platform_service.config import get_settings
from platform_service.db.models.content_block import ContentBlock
from platform_service.db.models.module_candidate_draft import ModuleCandidateDraft
from platform_service.db.models.source_page import SourcePage
from platform_service.db.repositories.module_candidate_repository import (
    ModuleCandidateRepository,
)
from platform_service.db.repositories.module_drafter_repository import (
    ModuleDrafterRepository,
)
from platform_service.services.card_drafter import (
    CardDrafter,
    CardDrafterError,
    CardDrafterResult,
)
from platform_service.services.module_card_validator import (
    ModuleCardValidator,
    annotate_field_flags,
)

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class StageDResult:
    """Outcome of Stage 2-draft for one candidate."""

    candidate_id: UUID
    module_id: UUID | None
    cards_count: int
    # Quiz is generated by a separate post-publish worker; Stage 2-draft
    # always returns 0 here. The pipeline_orchestrator will enqueue the
    # quiz worker on a non-None module_id.
    questions_count: int
    insufficient_reason: str | None


class StageDOrchestrator:
    def __init__(
        self,
        session: AsyncSession,
        *,
        card_drafter: CardDrafter | None = None,
        # Quiz / distractor-critique kwargs accepted for backwards-compat
        # with callers that still pass them; ignored here. Quiz generation
        # is now a post-publish Celery worker.
        quiz_drafter: object = None,
        distractor_critique: object = None,
    ) -> None:
        self._session = session
        self._candidate_repo = ModuleCandidateRepository(session)
        self._drafter_repo = ModuleDrafterRepository(session)
        self._card_drafter = card_drafter or CardDrafter()
        # Silence the unused-arg warnings without keeping references.
        del quiz_drafter, distractor_critique

    async def run(self, *, candidate_id: UUID, enqueue_post_publish: bool = True) -> StageDResult:
        """Execute Stage 2-draft for one candidate.

        `enqueue_post_publish` controls whether quiz + embedding generation
        Celery tasks are fired after the module is persisted. Default True
        preserves the existing per-doc ingestion flow. The cross-source
        fusion runner passes False because it may DELETE a freshly-drafted
        module on cross-source coverage failure, which races with the
        post-publish workers and produces FK violations on insert. The
        runner re-enqueues after coverage validation passes.
        """
        candidate = await self._candidate_repo.get_candidate(candidate_id)
        if candidate is None:
            raise ValueError(f"module_candidate_draft {candidate_id} not found")

        candidate_dict = self._candidate_to_dict(candidate)

        # 1. Load cited content_blocks
        cited_blocks, valid_block_ids = await self._load_cited_blocks(candidate_dict)
        if not cited_blocks:
            return StageDResult(
                candidate_id=candidate_id,
                module_id=None,
                cards_count=0,
                questions_count=0,
                insufficient_reason="no_cited_blocks_resolvable",
            )

        # 2. Card drafter
        try:
            card_result: CardDrafterResult = await self._card_drafter.draft(
                candidate=candidate_dict,
                cited_blocks=cited_blocks,
                valid_block_ids=valid_block_ids,
            )
        except CardDrafterError as exc:
            logger.exception("Stage 2-draft card drafter failed for candidate %s", candidate_id)
            raise exc
        if card_result.insufficient_reason:
            return StageDResult(
                candidate_id=candidate_id,
                module_id=None,
                cards_count=0,
                questions_count=0,
                insufficient_reason=card_result.insufficient_reason,
            )
        cards = card_result.cards

        # 3. Quality validator — drop hard violations, annotate soft warnings.
        validator = ModuleCardValidator()
        validated_cards: list[dict[str, Any]] = []
        for card in cards:
            res = validator.validate_card(card)
            if not res.is_valid:
                logger.warning(
                    "Stage 2-draft dropping card with hard violations cand=%s violations=%s",
                    candidate_id,
                    res.hard_violations,
                )
                continue
            if res.soft_warnings:
                card["field_flags"] = annotate_field_flags(card.get("field_flags"), card_result=res)
            validated_cards.append(card)
        cards = validated_cards

        settings = get_settings()
        if len(cards) < settings.card_min_count:
            return StageDResult(
                candidate_id=candidate_id,
                module_id=None,
                cards_count=0,
                questions_count=0,
                insufficient_reason="validator_dropped_too_many_cards",
            )

        # 4. Persist as auto-published module. Per the architecture reset
        # we do not stamp `primary_gap_id` here — Stage 2's prompt no
        # longer reasons about gaps, so any value would be guessed. The
        # dashboard's trigger-binding flow assigns gap → module mapping
        # post-publish, which is the canonical path.
        family = await self._drafter_repo.get_or_create_module_family(
            proposed_title=candidate_dict.get("proposed_title", "Untitled Module")
        )
        source_document_ids = self._extract_source_document_ids(candidate_dict)
        module = await self._drafter_repo.create_published_module(
            family=family,
            candidate=candidate_dict,
            cards=cards,
            source_document_ids=source_document_ids,
            primary_gap_id=None,
            quality_flags=candidate.quality_flags_jsonb,
        )
        await self._session.flush()
        # Capture the id locally before any commit-driven expiration.
        module_id = module.id

        # 5. Enqueue post-publish jobs. Wrapped in best-effort try/except so
        # the orchestrator does not fail the candidate when the broker is
        # unreachable — the module is already published and readable; the
        # dashboard can retry quiz/embedding generation manually.
        # Skipped when the caller is going to re-validate before keeping
        # the module (fusion runner's cross-source coverage retry).
        if enqueue_post_publish:
            self._enqueue_post_publish(module_id)

        return StageDResult(
            candidate_id=candidate_id,
            module_id=module_id,
            cards_count=len(cards),
            questions_count=0,
            insufficient_reason=None,
        )

    @staticmethod
    def _enqueue_post_publish(module_id: UUID) -> None:
        """Enqueue the post-publish quiz + embedding workers.

        Imported lazily so that orchestrator unit tests that mock the
        session don't need a real Redis broker — the import path itself
        loads `kombu` etc. when Celery is active.
        """
        try:
            from platform_service.celery_tasks import (
                generate_module_embedding_task,
                generate_module_quiz_task,
            )

            generate_module_quiz_task.delay(str(module_id))
            generate_module_embedding_task.delay(str(module_id))
        except Exception:
            logger.exception(
                "Stage 2-draft: failed to enqueue post-publish jobs for module %s "
                "(module is still published; retry from dashboard)",
                module_id,
            )

    # ── Internal helpers ────────────────────────────────────────────────

    @staticmethod
    def _candidate_to_dict(c: ModuleCandidateDraft) -> dict[str, Any]:
        return {
            "id": str(c.id),
            "ingestion_run_id": str(c.ingestion_run_id),
            "proposed_title": c.proposed_title,
            "scope_summary": c.scope_summary,
            "source_provenance": c.source_provenance_jsonb,
            "estimated_card_count": c.estimated_card_count,
            "estimated_quiz_count": c.estimated_quiz_count,
            "proposed_module_type": c.proposed_module_type,
            "previous_practice_summary": c.previous_practice_summary,
            "current_practice_summary": c.current_practice_summary,
            "rationale_summary": c.rationale_summary,
        }

    async def _load_cited_blocks(self, candidate: dict[str, Any]) -> tuple[list[dict[str, Any]], set[UUID]]:
        """Load every content_block referenced in the candidate's source_provenance."""
        block_ids: list[UUID] = []
        for entry in candidate.get("source_provenance", []) or []:
            for raw in entry.get("content_block_ids", []) or []:
                try:
                    block_ids.append(UUID(str(raw)))
                except ValueError:
                    continue
        if not block_ids:
            return [], set()
        # JOIN through source_page so each cited block carries its
        # source_document_id. The drafter prompt uses this to label blocks
        # by source — required for fused candidates whose cited_blocks
        # span multiple source_document_ids; harmless for single-source.
        result = await self._session.execute(
            select(ContentBlock, SourcePage.source_document_id)
            .join(SourcePage, ContentBlock.source_page_id == SourcePage.id)
            .where(ContentBlock.id.in_(block_ids))
        )
        rows = list(result.all())
        cited = [
            {
                "content_block_id": str(b.id),
                "source_document_id": str(sd_id),
                "block_type": b.block_type,
                "content_text": b.content_text,
                "content_language": b.content_language,
            }
            for b, sd_id in rows
        ]
        return cited, {b.id for b, _ in rows}

    @staticmethod
    def _extract_source_document_ids(candidate: dict[str, Any]) -> list[UUID]:
        ids: set[UUID] = set()
        for entry in candidate.get("source_provenance", []) or []:
            try:
                ids.add(UUID(str(entry["source_document_id"])))
            except (KeyError, ValueError):
                continue
        return sorted(ids)


__all__ = ["StageDOrchestrator", "StageDResult"]
